/** Shared Tailwind utility compositions for the admin workspace. */
export const adminTw = {
  surface: "min-h-screen bg-[#f5f4ef] font-sans text-base text-[#17251f]",
  shell: "grid min-h-screen grid-cols-[265px_minmax(0,1fr)] max-[980px]:grid-cols-[230px_minmax(0,1fr)] max-[720px]:block",
  sidebar: "sticky top-0 flex h-screen flex-col bg-[#0b1b33] px-4 pb-[18px] pt-7 text-[#c7d0df] max-[720px]:z-10 max-[720px]:h-auto max-[720px]:py-[13px]",
  brand: "grid justify-items-start gap-0.5 px-[9px] pb-5 text-white [&_img]:h-auto [&_img]:w-[170px] [&_small]:ml-[3px] [&_small]:text-[11px] [&_small]:text-[#8996aa] max-[720px]:p-0 max-[720px]:[&_img]:w-[135px] max-[720px]:[&_small]:hidden",
  nav: "grid gap-1 [&_a]:relative [&_a]:flex [&_a]:min-h-[46px] [&_a]:items-center [&_a]:gap-[13px] [&_a]:rounded-[7px] [&_a]:px-[13px] [&_a]:text-[15px] [&_a]:font-semibold [&_a]:text-[#c7d0df] [&_a:hover]:bg-[#142541] [&_a:hover]:text-white [&_a[aria-current=page]]:bg-[#1d2e49] [&_a[aria-current=page]]:text-white [&_a_i]:absolute [&_a_i]:right-[13px] [&_a_i]:h-[19px] [&_a_i]:w-1 [&_a_i]:rounded-[3px] [&_a_i]:bg-[#e1c451] max-[720px]:max-h-[calc(100vh-120px)] max-[720px]:overflow-y-auto max-[720px]:[&_a]:min-h-[42px]",
  mobileNav: "hidden max-[720px]:mt-3 max-[720px]:block [&_summary]:grid [&_summary]:min-h-[42px] [&_summary]:cursor-pointer [&_summary]:list-none [&_summary]:grid-cols-[22px_1fr_18px] [&_summary]:items-center [&_summary]:gap-2.5 [&_summary]:border [&_summary]:border-[#2b3d57] [&_summary]:px-3 [&_summary]:text-xs [&_summary]:text-white [&_summary::-webkit-details-marker]:hidden [&[open]>nav]:mt-2",
  desktopNav: "max-[720px]:hidden",
  publicLink: "mt-auto flex min-h-[42px] items-center gap-[11px] border border-[#263750] px-2.5 text-[13px] font-semibold text-[#c7d0df] hover:border-[#516079] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#e1c451] max-[720px]:hidden",
  account: "mt-3.5 grid grid-cols-[34px_1fr_auto] items-center gap-2.5 border-t border-[#263750] px-2 pt-[18px] max-[720px]:hidden",
  main: "min-w-0",
  pageContent: "mx-auto w-[min(calc(100%_-_72px),1180px)] py-14 pb-20 max-[980px]:w-[min(calc(100%_-_44px),1180px)] max-[720px]:w-[min(calc(100%_-_32px),1180px)] max-[720px]:py-[38px] max-[720px]:pb-[60px]",
  editorPage: "max-w-[980px]",
  pageHeader: "flex min-h-[86px] items-end justify-between gap-6 border-b border-[#cfd1ca] pb-6 [&_h1]:m-0 [&_h1]:font-sans [&_h1]:text-[clamp(42px,5vw,60px)] [&_h1]:font-normal [&_h1]:leading-[.9] [&_h1]:tracking-[-.035em] [&>div>p]:mb-1.5 [&>div>p]:text-[13px] [&>div>p]:font-bold [&>div>p]:text-[#496057] [&>span]:text-[13px] [&>span]:text-[#68756f] max-[720px]:min-h-[70px] max-[720px]:pb-[18px] max-[720px]:[&>span]:hidden",
  headerBackLink: "mb-2.5 inline-flex w-fit items-center gap-[7px] text-sm font-semibold text-[#496057] hover:text-[#153c2e] hover:underline hover:underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-[3px] focus-visible:outline-[#153c2e]",
  headerActions: "flex items-center gap-[18px] [&>span]:text-[13px] [&>span]:text-[#68756f] [&>a]:inline-flex [&>a]:min-h-11 [&>a]:items-center [&>a]:gap-2 [&>a]:bg-[#153c2e] [&>a]:px-4 [&>a]:text-[13px] [&>a]:font-bold [&>a]:text-white max-[720px]:[&>span]:hidden max-[720px]:[&>a]:min-h-[42px] max-[720px]:[&>a]:px-3",
  filters: "flex items-center gap-2.5 py-6 [&>label]:flex [&>label]:min-h-11 [&>label]:flex-1 [&>label]:items-center [&>label]:gap-2.5 [&>label]:border [&>label]:border-[#c9cbc4] [&>label]:bg-[#fffefb] [&>label]:px-[13px] [&>label]:text-[#738079] [&_input]:w-full [&_input]:border-0 [&_input]:bg-transparent [&_input]:text-sm [&_input]:text-[#17251f] [&_input]:outline-none [&>select]:min-h-11 [&>select]:border [&>select]:border-[#c9cbc4] [&>select]:bg-[#fffefb] [&>select]:px-3.5 [&>select]:text-[13px] [&>button]:min-h-11 [&>button]:cursor-pointer [&>button]:border [&>button]:border-[#153c2e] [&>button]:bg-[#153c2e] [&>button]:px-3.5 [&>button]:text-[13px] [&>button]:font-bold [&>button]:text-white [&>a]:text-[13px] [&>a]:text-[#53645c] [&>a]:underline [&>a]:underline-offset-4 max-[720px]:grid max-[720px]:grid-cols-2 max-[720px]:[&>label]:col-span-full max-[720px]:[&>a]:justify-self-start",
  resultsCount: "mb-2.5 text-xs text-[#68756f]",
  notice: "mt-[22px] border border-[#aac2b7] bg-[#e9f0ec] px-4 py-[13px] text-[13px] text-[#204e3a]",
  noticeError: "border-[#d9aaa6] bg-[#f6e9e7] text-[#8a2c25]",
  table: "border-t border-[#17251f]",
  tableHead: "grid min-h-[42px] grid-cols-[minmax(260px,1.5fr)_minmax(150px,1fr)_120px_110px_132px] items-center gap-[18px] text-[11px] font-bold text-[#68756f] max-[980px]:grid-cols-[minmax(230px,1.5fr)_minmax(130px,1fr)_105px_112px] max-[980px]:[&>span:nth-child(4)]:hidden max-[720px]:hidden",
  row: "grid min-h-[82px] grid-cols-[minmax(260px,1.5fr)_minmax(150px,1fr)_120px_110px_132px] items-center gap-[18px] border-t border-[#d4d5ce] max-[980px]:grid-cols-[minmax(230px,1.5fr)_minmax(130px,1fr)_105px_112px] max-[980px]:[&>p:nth-child(4)]:hidden max-[720px]:grid-cols-[1fr_auto] max-[720px]:gap-[13px] max-[720px]:py-5 max-[720px]:[&>p]:col-start-1 max-[720px]:[&>p]:m-0 max-[720px]:[&>p]:grid max-[720px]:[&>p]:grid-cols-[90px_1fr] max-[720px]:[&>p:nth-child(4)]:grid max-[720px]:[&>p]:before:font-bold max-[720px]:[&>p]:before:text-[#374a41]",
  publicationGrid: "grid-cols-[minmax(360px,2.2fr)_minmax(95px,.6fr)_120px_110px_132px] gap-3 max-[980px]:grid-cols-[minmax(300px,2fr)_minmax(90px,.55fr)_105px_112px] max-[980px]:gap-2.5 max-[720px]:grid-cols-[1fr_auto]",
  clickableRow: "cursor-pointer hover:bg-[#f5f4ef]",
  personName: "flex min-w-0 items-center gap-[13px] [&>div]:min-w-0 [&>div]:flex-1 [&>span]:grid [&>span]:h-10 [&>span]:w-10 [&>span]:shrink-0 [&>span]:place-items-center [&>span]:rounded-full [&>span]:bg-[#e7e8e2] [&>span]:text-xs [&>span]:font-bold [&>span]:text-[#36594b] [&>img]:h-10 [&>img]:w-10 [&>img]:shrink-0 [&>img]:rounded-full [&>img]:object-cover [&_strong]:block [&_strong]:w-full [&_strong]:truncate [&_strong]:font-sans [&_strong]:text-[21px] [&_strong]:font-semibold [&_small]:mt-0.5 [&_small]:block [&_small]:w-full [&_small]:truncate [&_small]:text-xs [&_small]:text-[#68756f] max-[720px]:col-start-1",
  rowMeta: "mt-0.5 text-xs text-[#68756f] max-[720px]:before:content-[attr(data-label)] max-[720px]:before:font-bold max-[720px]:before:text-[#374a41]",
  rowActions: "relative flex justify-end gap-1.5 max-[720px]:col-start-2 max-[720px]:row-start-1 [&>a]:grid [&>a]:h-[34px] [&>a]:w-[34px] [&>a]:place-items-center [&>a]:border [&>a]:border-[#d4d5ce] [&>a]:text-[#52635b] [&>a:hover]:border-[#153c2e] [&>a:hover]:text-[#153c2e] [&>button]:grid [&>button]:h-[34px] [&>button]:w-[34px] [&>button]:cursor-pointer [&>button]:place-items-center [&>button]:border [&>button]:border-[#d4d5ce] [&>button]:bg-transparent [&>button]:text-[#52635b] [&>button:hover]:border-[#153c2e] [&>button:hover]:text-[#153c2e]",
  deleteConfirm: "absolute right-0 top-10 z-[4] flex w-[230px] justify-end gap-[7px] border border-[#c9cbc4] bg-[#fffefb] p-2.5 shadow-[0_10px_25px_rgba(11,27,51,.12)] [&>button]:grid [&>button]:h-[34px] [&>button]:w-[34px] [&>button]:cursor-pointer [&>button]:place-items-center [&>button]:border [&>button]:border-[#d4d5ce] [&>button]:bg-transparent [&>button]:p-0 [&>button]:text-[#52635b] [&>form]:flex-1 [&>form_button]:min-h-[34px] [&>form_button]:w-full [&>form_button]:border [&>form_button]:border-[#9d3028] [&>form_button]:bg-[#9d3028] [&>form_button]:px-2.5 [&>form_button]:text-[11px] [&>form_button]:font-bold [&>form_button]:text-white",
  pagination: "mt-6 flex items-center justify-between gap-3 border-t border-[#e5e0d5] pt-4 text-[13px] [&_p]:m-0 [&_p]:font-medium [&_p]:text-[#68756f] [&_a]:inline-flex [&_a]:items-center [&_a]:gap-1.5 [&_a]:rounded-md [&_a]:border [&_a]:border-[#ded8cc] [&_a]:bg-white [&_a]:px-3.5 [&_a]:py-[7px] [&_a]:font-medium [&_a]:text-[#33473e] [&_a]:transition-colors [&_a:hover]:border-[#c9c2b3] [&_a:hover]:bg-[#ebe6dc] [&>span]:inline-flex [&>span]:cursor-not-allowed [&>span]:items-center [&>span]:gap-1.5 [&>span]:rounded-md [&>span]:border [&>span]:border-[#ede9df] [&>span]:bg-[#f8f6f0] [&>span]:px-3.5 [&>span]:py-[7px] [&>span]:font-medium [&>span]:text-[#b3ab9c]",
  inlineState: "flex items-start gap-[15px] border border-[#d4d5ce] bg-[#fffefb] p-[26px] [&>svg]:text-[#496057] [&_h2]:m-0 [&_h2]:font-sans [&_h2]:text-2xl [&_h2]:font-medium [&_p]:mt-1.5 [&_p]:text-sm [&_p]:text-[#68756f]",
  emptyState: "mt-[34px] flex min-h-[360px] flex-col items-center justify-center border border-[#d4d5ce] bg-[#fffefb] p-10 text-center [&>span]:mb-[18px] [&>span]:grid [&>span]:h-[54px] [&>span]:w-[54px] [&>span]:place-items-center [&>span]:border [&>span]:border-[#cfd1ca] [&>span]:text-[#36594b] [&_h2]:m-0 [&_h2]:font-sans [&_h2]:text-2xl [&_h2]:font-medium [&_p]:mt-1.5 [&_p]:max-w-[380px] [&_p]:text-sm [&_p]:text-[#68756f] max-[720px]:min-h-[300px] max-[720px]:p-7",
  retryButton: "mt-5 inline-flex min-h-11 cursor-pointer items-center gap-2 border-0 bg-[#153c2e] px-[15px] text-[13px] font-bold text-white",
  editorForm: "mt-[30px] [&>section]:border [&>section]:border-[#d4d5ce] [&>section]:bg-[#fffefb]",
  formHeading: "flex justify-between gap-[30px] border-b border-[#d4d5ce] px-7 py-6 [&_h2]:m-0 [&_h2]:font-sans [&_h2]:text-[30px] [&_h2]:font-medium [&_p]:mt-1.5 [&_p]:max-w-[410px] [&_p]:text-[13px] [&_p]:text-[#68756f] max-[720px]:block max-[720px]:px-5 max-[720px]:py-[22px]",
  formGrid: "grid grid-cols-2 items-start gap-x-6 gap-y-[22px] p-7 [&>label]:grid [&>label]:grid-rows-[auto_1fr] [&>label]:gap-2 [&>label]:text-[13px] [&>label]:font-bold [&>label]:text-[#33473e] [&_input:not([type=checkbox])]:box-border [&_input:not([type=checkbox])]:min-h-12 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#c7cac3] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-[13px] [&_input:not([type=checkbox])]:py-[11px] [&_input:not([type=checkbox])]:text-sm [&_input:not([type=checkbox])]:font-normal [&_input:not([type=checkbox])]:text-[#17251f] [&_input:not([type=checkbox])]:outline-none [&_select]:box-border [&_select]:min-h-12 [&_select]:w-full [&_select]:border [&_select]:border-[#c7cac3] [&_select]:bg-white [&_select]:px-[13px] [&_select]:py-[11px] [&_select]:text-sm [&_select]:font-normal [&_select]:text-[#17251f] [&_select]:outline-none [&_textarea]:min-h-[150px] [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:border [&_textarea]:border-[#c7cac3] [&_textarea]:bg-white [&_textarea]:px-[13px] [&_textarea]:py-[11px] [&_textarea]:text-sm [&_textarea]:font-normal [&_textarea]:leading-[1.55] [&_textarea]:text-[#17251f] [&_textarea]:outline-none [&_input:focus]:border-[#153c2e] [&_input:focus]:shadow-[0_0_0_2px_rgba(21,60,46,.12)] [&_select:focus]:border-[#153c2e] [&_select:focus]:shadow-[0_0_0_2px_rgba(21,60,46,.12)] [&_textarea:focus]:border-[#153c2e] [&_textarea:focus]:shadow-[0_0_0_2px_rgba(21,60,46,.12)] max-[720px]:grid-cols-1 max-[720px]:p-5",
  fieldFull: "col-span-full max-[720px]:col-auto",
  required: "text-[11px] font-normal text-[#7a857f]",
  fieldHelp: "flex items-center gap-1.5 text-xs font-normal leading-[1.4] text-[#68756f]",
  fieldHelpError: "text-[#8a2c25]",
  checkbox: "!flex items-start !gap-[11px] pt-1 [&>input]:mt-[3px] [&>input]:h-[17px] [&>input]:w-[17px] [&>input]:accent-[#153c2e] [&_strong]:block [&_small]:mt-[3px] [&_small]:block [&_small]:text-xs [&_small]:font-normal [&_small]:text-[#68756f]",
  editorError: "mt-4 border border-[#d9aaa6] bg-[#f6e9e7] px-4 py-[13px] text-[13px] text-[#8a2c25]",
  formActions: "flex flex-wrap items-center justify-end gap-3.5 pb-1 pt-[22px] [&>a]:text-[13px] [&>a]:text-[#53645c] [&>a]:underline [&>a]:underline-offset-4 [&_button]:inline-flex [&_button]:min-h-12 [&_button]:cursor-pointer [&_button]:items-center [&_button]:gap-2 [&_button]:border-0 [&_button]:bg-[#153c2e] [&_button]:px-[18px] [&_button]:text-[13px] [&_button]:font-bold [&_button]:text-white [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-60 max-[720px]:flex-col-reverse max-[720px]:items-stretch max-[720px]:gap-2.5 max-[720px]:px-5 max-[720px]:pb-1 max-[720px]:pt-[18px] max-[720px]:[&>a]:text-center max-[720px]:[&_button]:w-full max-[720px]:[&_button]:justify-center",
  spin: "animate-spin motion-reduce:animate-none",
  skeleton: "animate-pulse bg-[#e1e3dd] motion-reduce:animate-none",
} as const;

export function statusTw(status: string) {
  const tone = status === "published"
    ? "border-[#a9c0b6] bg-[#e9f0ec] text-[#204e3a]"
    : status === "preview"
      ? "border-[#d9ca91] bg-[#f7f0d9] text-[#6b5814]"
      : status === "draft"
        ? "bg-[#eeeee9]"
        : "";
  return `inline-flex rounded-[20px] border border-[#c8cbc4] px-2 py-1 text-[11px] not-italic capitalize text-[#53645c] ${tone}`;
}
